#include "Adafruit_GFX.h"
#include "Adafruit_ILI9341.h"


#ifndef CONSTS_H
#define CONSTS_H





#define TFT_DC 9
#define TFT_CS 10
#define TFT_MOSI 11
#define TFT_MISO 12
#define TFT_CLK 13
#define TFT_RST 8

#define SLOT_WIDTH 80
#define TFT_HEIGHT 240
#define TFT_WIDTH 320




#define MAX_TEMPERATURE 50
#define MIN_INITIAL_VOLTAGE 2.0
#define MAX_RESISTANCE 300
#define MIN_CAPACITY 200
#define MIN_EFFICIENCY 0.7
// #define DISCHARGE_CUTOFF_VOLTAGE 3.1
#define DISCHARGE_CUTOFF_VOLTAGE 2.0


#define CHARGING_TIMEOUT 2*3600 // seconds

#define ADS_LOWER_CHANNELS 0
#define ADS_HIGHER_CHANNELS 1



#define COLOR_WAIT ILI9341_DARKGREY
#define COLOR_WAIT_FRONT  ILI9341_WHITE

#define COLOR_CHARGING ILI9341_CYAN
#define COLOR_CHARGING_FRONT ILI9341_BLACK

#define COLOR_MEASURE_RI ILI9341_PINK
#define COLOR_MEASURE_RI_FRONT ILI9341_BLACK

#define COLOR_DISCHARGE ILI9341_ORANGE
#define COLOR_DISCHARGE_FRONT ILI9341_BLACK


#define COLOR_FAULT ILI9341_RED
#define COLOR_FAULT_FRONT ILI9341_WHITE

#define COLOR_VOLTAGE ILI9341_WHITE
#define COLOR_CURRENT ILI9341_WHITE
#define COLOR_TEMPERATURE ILI9341_WHITE

#define COLOR_RECHARGE 7
#define COLOR_DONE ILI9341_GREEN

// -------------------------
#define STATE_WAIT 1
#define STATE_INSERTED_SETTLE 2
#define STATE_BARCODE_WAIT 3
#define STATE_CHARGING 4
#define STATE_MEASURE_RI 5
#define STATE_DISCHARGE 6
#define STATE_RECHARGE 7
#define STATE_DONE 8
#define STATE_FAULT 10


#define FAULT_HIGH_TEMPERATURE 1
#define FAULT_CHARGETIMEOUT 2
#define FAULT_HIGH_RESISTANCE 3
#define FAULT_LOW_CAPACITY 4
#define FAULT_LOW_EFFICIENCY 5


#endif